name: forum_livros
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Todos os pacotes ficam neste nível
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.1
  cupertino_icons: ^1.0.6 # <-- Atualizei para a versão 1.0.6 (Null Safety)

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
# ... resto do arquivo
