name: forum_livros
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  firebase_storage: ^12.1.0
  firebase_messaging: ^15.0.2
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
